### ISSUE TITLE
NetworkClient.get() does not work

### ISSUE THREAD

**Issue by brownmk** [idekerlab/py2cytoscape#12]
line 138 of network_client.py: return requests.get(self.__url + '/' + str(id) + '.json').json()
 Does not seem to work. networks/52.json does not seem to be supported by CyREST API.
 Maybe change it into:
 return requests.get(self.__url + '/' + str(id)).json()

**Comment by keiono** [comment]
Fixed in current development branch.  v0.5.0 will be released later today.
