### ISSUE TITLE
importing sif like pandas dataframe

### ISSUE THREAD

**Issue by kozo2** [idekerlab/py2cytoscape#9]
I would like to offer a feature like this issue title.
"sif like pandas dataframe" is 3 column dataframe.
- 1st column is source node
- 2nd column interaction type
- 3rd column is target node

**Comment by keiono** [comment]
This will be available in 0.4.0.

DataFrame utility will supports:

* Convert data from DataFrame to cytoscape.js JSON
* Update tables from DataFrame
* Create Table from DataFrame

**Comment by keiono** [comment]
This can be done by from_dataframe method now.
